###
# This file only exists for the purposes of
# testing context with the {{partial}} helper.
###

# Build
root: _gh_pages
dest: <%= site.root %>


# Site metadata
brand: ASSEMBLE
title: Assemble
lead: The most awe inspiring website in Northern Kentucky.
description: >
  Static site generator for Grunt.js and Yeoman. Assemble makes it dead simple to build modular sites,
  blogs, gh-pages, components and documentation from reusable templates and data.
license:
  type: MIT License
  url: ./license/index.html


# URLs
repo: https://github.com/assemble/assemble
download:
  source: https://github.com/assemble/assemble/archive/master.zip